# Generated by Django 5.0.2 on 2024-04-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="areasido",
            old_name="name",
            new_name="sido_name",
        ),
        migrations.RenameField(
            model_name="areasigungu",
            old_name="name",
            new_name="sigungu_name",
        ),
    ]
