# Generated by Django 5.0.2 on 2024-05-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_name", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=100)),
                ("area", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("capacity_count", models.IntegerField()),
                ("location", models.CharField(max_length=3)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
