# Generated by Django 5.0.2 on 2024-04-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelterdb", "0006_shelter_capacity_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shelter",
            name="capacity_count",
        ),
    ]
